name: Windows Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows-test:
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      fail-fast: false
      matrix:
        target:
        - arch: 'x64'
          programFiles: 'C:\Program Files'
        - arch: 'x86'
          programFiles: 'C:\Program Files (x86)'
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup .NET Sdk
      run: |
        echo 'PROCESSOR_ARCHITEW6432=${{ matrix.target.arch }}' >> $env:GITHUB_ENV
        Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1';      
        ./dotnet-install.ps1 -Channel 6.0 -Architecture ${{ matrix.target.arch }} -InstallDir "${{ matrix.target.programFiles }}\dotnet"
        ./dotnet-install.ps1 -Channel 7.0 -Architecture ${{ matrix.target.arch }} -InstallDir "${{ matrix.target.programFiles }}\dotnet"
        ./dotnet-install.ps1 -Channel 8.0 -Architecture ${{ matrix.target.arch }} -InstallDir "${{ matrix.target.programFiles }}\dotnet"
        ./dotnet-install.ps1 -Channel 9.0 -Architecture ${{ matrix.target.arch }} -InstallDir "${{ matrix.target.programFiles }}\dotnet"
        dotnet --list-sdks
    #- name: Setup .NET Sdk
    #  uses: actions/setup-dotnet@v3
    #  with:
    #    dotnet-version: |
    #        3.1.x
    #        5.x
    #        6.x
    #        7.x
    #        8.x    
    - name: Test .NET 9 ${{ matrix.target.arch }}
      run: dotnet test -v quiet -f net9.0 --blame-crash --blame-hang-dump-type=mini --logger "trx;LogFilePrefix=testResults;verbosity=detailed" --nologo /nologo --runtime win-${{ matrix.target.arch }}
    - name: Test .NET 8 ${{ matrix.target.arch }}
      run: dotnet test -v quiet -f net8.0 --blame-crash --blame-hang-dump-type=mini --logger "trx;LogFilePrefix=testResults;verbosity=detailed" --nologo /nologo --runtime win-${{ matrix.target.arch }}
    - name: Test .NET 7 ${{ matrix.target.arch }}
      run: dotnet test -v quiet -f net7.0 --blame-crash --blame-hang-dump-type=mini --logger "trx;LogFilePrefix=testResults;verbosity=detailed" --nologo /nologo --runtime win-${{ matrix.target.arch }}
    - name: Test .NET 6 ${{ matrix.target.arch }}
      run: dotnet test -v quiet -f net6.0 --blame-crash --blame-hang-dump-type=mini --logger "trx;LogFilePrefix=testResults;verbosity=detailed" --nologo /nologo --runtime win-${{ matrix.target.arch }}
    - name: Test Results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.target.arch }}-test-results
        if-no-files-found: ignore
        path: |
            **/TestResults/**
            **/*.dmp
